# Generated by Django 5.0.14 on 2026-06-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(max_length=500)),
                ('full_name', models.CharField(max_length=255)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('tech_stack', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('file_tree', models.JSONField(default=dict)),
                ('file_count', models.IntegerField(default=0)),
                ('total_size', models.IntegerField(default=0)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
