# Generated by Django 5.0.14 on 2026-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='status',
            field=models.CharField(default='ready', max_length=20),
        ),
    ]
