# Generated by Django 5.0.14 on 2026-06-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_repository_error_message_repository_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
