# Generated by Django 5.0.14 on 2026-06-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_userprofile_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='source',
            field=models.CharField(default='public_url', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_full_agent_access',
            field=models.BooleanField(default=False),
        ),
    ]
